.TH _printf 1 2019-10-29 Linux "_printf Manual Page"
.SH NAME
.B _printf 
- print formatted strings
.SH SYNOPSIS
.B #include """holberton.h""" 
.B #include <stdarg.h>
.PP
.B int _printf(const char *\fIformat, ...\fR);
.SH DESCRIPTION
.B The _printf function will print formatted strings to the screen.
.PP
.B Return Value
.PP
If successful, _printf will return the number of characters printed, excluding the null byte.
.PP
If _printf encounters an error, return value will be negative. 
.PP
.SH OPTIONS
.B The flag characters
"' '" + # -
.PP
.B Field Width
.PP
.B Precision
.PP
.B Length modifier
.PP
.B Conversion Specifier
o, u, x, X
.SH EXAMPLES
.PP
.nf
.RS
.RE
.fi
.PP
.SH ENVIRONMENT
A list of all environment variables that affect the program or function and how they affect it
.SH FILES
A list of the files the program function uses, such as config files, startup files, and files the program directly operates on
Give full pathname of these files, and use the install process to mod the dir part to match the user pref.
/usr/local is base
.SH BUGS
A list of limitations, known defects or inconveniences
.SH SEE ALSO
A comma separated list of related man pages, ordered by section number and alphabetical, not terminated with a period
.SH AUTHORS
Justin Majetich & Kati Fredlund
